name: NuGet
on:
  push:
    branches:
      - master

jobs:
  nuget-1:
    name: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GHTOKEN}}
      - name: Pack
        run: |
          dotnet pack -c Release --output nupkgs BeatTogether.Extensions.Autobus.RabbitMQ/BeatTogether.Extensions.Autobus.RabbitMQ.csproj
          dotnet pack -c Release --output nupkgs BeatTogether.Extensions.BinaryRecords/BeatTogether.Extensions.BinaryRecords.csproj
          dotnet pack -c Release --output nupkgs BeatTogether.Extensions.Configuration/BeatTogether.Extensions.Configuration.csproj
          dotnet pack -c Release --output nupkgs BeatTogether.Extensions.LiteNetLib/BeatTogether.Extensions.LiteNetLib.csproj
          dotnet pack -c Release --output nupkgs BeatTogether.Extensions.Serilog/BeatTogether.Extensions.Serilog.csproj
          dotnet pack -c Release --output nupkgs BeatTogether.Extensions.StackExchange.Redis/BeatTogether.Extensions.StackExchange.Redis.csproj
      - name: Publish
        run: |
          dotnet nuget push "nupkgs/BeatTogether.Extensions.*.nupkg" -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate

  nuget-2:
    name: https://api.nuget.org/v3/index.json
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      - name: Pack
        run: |
          dotnet pack -c Release --output nupkgs BeatTogether.Extensions.Autobus.RabbitMQ/BeatTogether.Extensions.Autobus.RabbitMQ.csproj
          dotnet pack -c Release --output nupkgs BeatTogether.Extensions.BinaryRecords/BeatTogether.Extensions.BinaryRecords.csproj
          dotnet pack -c Release --output nupkgs BeatTogether.Extensions.Configuration/BeatTogether.Extensions.Configuration.csproj
          dotnet pack -c Release --output nupkgs BeatTogether.Extensions.LiteNetLib/BeatTogether.Extensions.LiteNetLib.csproj
          dotnet pack -c Release --output nupkgs BeatTogether.Extensions.Serilog/BeatTogether.Extensions.Serilog.csproj
          dotnet pack -c Release --output nupkgs BeatTogether.Extensions.StackExchange.Redis/BeatTogether.Extensions.StackExchange.Redis.csproj
      - name: Publish
        run: |
          dotnet nuget push "nupkgs/BeatTogether.Extensions.*.nupkg" -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
